# Generated by Django 3.1.1 on 2020-09-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfield',
            old_name='full_name',
            new_name='name',
        ),
    ]
