# Generated by Django 3.1.1 on 2020-09-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authour', '0002_auto_20200923_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentfield',
            old_name='photo',
            new_name='document',
        ),
    ]
