# Generated by Django 3.1.1 on 2020-09-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authour', '0003_auto_20200923_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfield',
            name='phone',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='pincode',
            field=models.CharField(default='', editable=False, max_length=6),
        ),
    ]
